name: Develop Task Workflow

on:
  push:
    branches:
      - "t0**"
      - "fix-**"

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.13.2"

      - name: Cache dependencies
        run: deno cache --unstable ./deps.ts

      - name: Run formatter
        run: deno fmt
        
      - name: Run linter
        run: deno lint
