name: Testing Workflow

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.13.2"

      - name: Cache dependencies
        run: deno cache --unstable ./deps.ts

      - name: Run tests
        run: deno test -c ./tsconfig.json --allow-net --allow-env --allow-read --unstable
